cad.php
js/openCad.js

Fixes the well known issue regarding sub-directory incompatibility in #52.
Huge shoutout to @gfdking on Twitter for this sadly simple fix.

Fix sub-directory bug.

---

mdt.php

Temporarily omit MDT Status.

---

actions/adminActions.php
actions/api.php
actions/civActions.php
actions/dispatchActions.php
actions/login.php
actions/logout.php
actions/ncic.php
actions/ncicAdminActions.php
actions/permissions.php
actions/profileActions.php
actions/register.php
actions/responderActions.php
cad.php
civilian.php
mdt.php
oc-admin/admin.php
oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php
profile.php

Readded api.php + Fixed Links for actions and oc-admin folders + Fixed civilian.php

---

README.md

Fixing spelling mistakes in the README (#66)

---

actions/responderActions.php
oc-admin/admin.php
oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php
profile.php

* Fixing variable in various files
*  Remove superfluous backtick in profile.php

Fixing variable in various files and removing superfluous backtick

---

oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php
profile.php

- Removing refernces to actions/direction.php. (#86)
- Moved dashboard button to sidebar. (#86)

Removing more references to actions/direction.php

---

actions/profileActions.php

profileActions.php fixed redirect

---

cad.php
civilian.php
dashboard.php
index.php
mdt.php
oc-admin/admin.php
oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php
oc-config.sample.php
oc-includes/header.inc.php
oc-includes/jquery-colsolidated.inc.php
profile.php

* Breaking heads in to oc-includes/header.inc.php
* Breaking tails in to oc-includes/jquery-colsolidated.inc.php
* Improved documentation for BASE_URL in oc-config.sample.php
* Removed BASE_DIR due to redundancy.

Making heads and tails modular

---

actions/profileActions.php

Reverts StormlightTech/openCAD-php#96

Revert "profileActions.php fixed redirect"

---

oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/userManagement.php

Fixed headers for callhistory, ncicadmin, & usermanagement php files

---

oc-includes/header.inc.php

Stops links from opening in new page

---

oc-admin/admin.php
oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php

@murfasa Fixed the admin page sidebar not taking you to the correct page.

Admin Sidebar URL Fix

---

mdt.php
reset-password.php

- (#95) Password reset added and working.
- Removed a useless section from mdt.php, no reason it should of been there in the first place.

added password reset, cleaned up mdt.php

---

README.md
actions/adminActions.php
actions/api.php
actions/civActions.php
cad.php
civilian.php
dashboard.php
index.php
mdt.php
reset-password.php

Formatted the HTML, It works.. I think?

Cleaned up HTML

---

openCad_Initialization.sql
profile.php

Removed ranks from profile and sql.

Removed Ranks

---

openCad_Initialization.sql

Removed the alter table for ranks which were not removed before.

Removed Ranks again

---

actions/adminActions.php
cad.php
civilian.php
index.php
mdt.php
oc-admin/admin.php
oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php
profile.php

- (#112)
- Well more redirection fixes... this should be pretty much all of them fixed.. i hope.

More redirection fixes

---

actions/adminActions.php
actions/api.php
js/openCad.js
mdt.php
oc-admin/admin.php
oc-admin/userManagement.php

- Quick accept now works. (Partially #112 , #70 , #68 , #1 )
- Cleaned up Call Details, Narrative will be added back sooner or later.

Quick Accept Fixed

---

actions/api.php
cad.php
openCad_Initialization.sql

Added Incident types into the database.

Incident Types/Codes

---

cad.php

Fixed call details for CAD from #138

Fixed Call Details (CAD)

---

README.md

added support for windows and cpanel

[update] made some changes to readme.md

---

README.md

Fixed a error with spacing in title

[Correction to previous update] new changes to readme.md

---

README.md

* Fixing some grammatical errors.
* Consolidating support notes.
* Adding links to JIRA and discord channels.

Fixing headers and elaborating on Support

---

openCad_Initialization.sql

* Add all 243 streets to the database (Source: http://gta.wikia.com/wiki/List_of_Street_Names)
(Team: Please refer to JIRA before doing anything here.)

Adding Streets, all 243

---

oc-admin/admin.php
oc-admin/callhistory.php
oc-admin/ncicAdmin.php
oc-admin/oc-admin-includes/sidebarNav.inc.php
oc-admin/permissionManagement.php
oc-admin/userManagement.php

OCPHP-131 #comment This will make adding admin pages easier in future  #resolve

---

oc-admin/oc-admin-includes/sidebarNav.inc.php
oc-includes/header.inc.php

Made About OpenCAD a button to go to the about page. Removed Home category. Fixed default page on the sidebar.

Various Admin Sidebar Fixes/Changes

---

actions/api.php
cad.php
dashboard.php
openCad_Initialization.sql

Made streets and incidents get called from the database for new calls in the CAD. Added EMS and State Police for users to be.

Streets and Incidents called from Database

---

dashboard.php

Fixed minor mistake with EMS button on dashboard

EMS Button Fix

---

OpenCAD-php
cad.php
civilian.php
dashboard.php
index.php
mdt.php
oc-config.sample.php
oc-functions.php
profile.php
reset-password.php

* Improved inline docs for oc-config.sample.php to make things like BASE_URL more easy to understand
* Added HASH block for future implementation.
* moved ABSPATH function into oc-config.sample.php and included oc-functions.php there as well.

Improved inline docs for oc-config.sample.php

---

OpenCAD_Initialization.sql
civilian.php

Fixed the genders saving to the database

Fixed Genders Saving

---

actions/api.php

Found session_start error while testing. Should be fixed.

Fixed session_start error

---

actions/api.php

Removed an unnecessary session_start.

Removed session_start

---

index.php

ReAdded ems selection back to the request access section.

ReAdded EMS button to Request Access

---

index.php

Fixed 500 error that everyone was getting. Invalid string concatenation at line 15. Included an extra dot in the path causing oc-config.php to not properly load.

Fixed 500 error.

---

actions/adminActions.php
actions/api.php
actions/civActions.php
actions/dispatchActions.php
actions/login.php
actions/logout.php
actions/ncic.php
actions/ncicAdminActions.php
actions/permissions.php
actions/profileActions.php
actions/register.php
actions/responderActions.php
mdt.php
oc-admin/ncicAdmin.php
oc-admin/userManagement.php

Did some stuff in MDT with auto-updating My Calls and BOLOs. Nice fancy little audio noise when you are added to a call. Also fixed some all (hopefully) of the subdirectory issues.

MDT changes and sub dir issues

---

OpenCAD_Initialization.sql
actions/api.php
actions/dispatchActions.php
actions/responderActions.php
cad.php
mdt.php

Added Narrative back to call details. Fixed some issues people were having in the MDT. New Call tone when added to a call.

Narrative and MDT Stuff

---

actions/adminActions.php
actions/civActions.php
actions/dispatchActions.php
actions/responderActions.php
cad.php
civilian.php
mdt.php
oc-admin/userManagement.php
profile.php

Merry Christmas :)
We have added the ability to edit users, edit BOLOs, edit civilian identities and vehicles.
When you get added to a call you hear a tone.
Fixes:
New call tone being heard when entering MDT.
Fixed subdirectory/redirect errors.

RC3 - Edit Stuff, etc.
